export const gamePhases = {
  GENERATE_RESOURCES: 'GENERATE_RESOURCES',
  // TRADE_RESOURCES: 'TRADE_RESOURCES',
  POPULATE_PLANETS: 'POPULATE_PLANETS',
  POPULATE_MONUMENTS: 'POPULATE_MONUMENTS',
  PURCHASE_DEVELOPMENTS: 'PURCHASE_DEVELOPMENTS',
}
