export default {
  mrRobot: {
    id: 'mrRobot',
    name: 'Mr. Robot',
    effect: 'Hack one additional terminal after final hack',
    points: 2,
    cost: 10,
  },
  ozoneStabalizer: {
    id: 'ozoneStabalizer',    
    name: 'Ozone Stabalizer',
    effect: 'Global Warming has no effect',
    points: 2,
    cost: 10,
  },
  soylentGenerator: {
    id: 'soylentGenerator',    
    name: 'Soylent Generator',
    effect: '+1 Soylent, Soylent Hack',
    points: 3,
    cost: 15,
  },
  pandoraGateway: {
    id: 'pandoraGateway',    
    name: 'Pandora Gateway',
    effect: '+1 unobtanium, if collecting unobtanium',
    points: 3,
    cost: 15,
  },
  umbrellaCorporation: {
    id: 'umbrellaCorporation',    
    name: 'Umbrella Corporation',
    effect: 'Biological Warfare has no effect',
    points: 3,
    cost: 15,
  },
  cryptoMiner: {
    id: 'cryptoMiner',    
    name: 'Crypto Miner',
    effect: 'Credits are worth 14 instead of 7',
    points: 4,
    cost: 20,
  },
  spaceVaults: {
    id: 'spaceVaults',    
    name: 'Space Vaults',
    effect: 'No need to discard resources',
    points: 4,
    cost: 20,
  },
  v: {
    id: 'v',    
    name: 'V',
    effect: 'Fascism effects opponents',
    points: 6,
    cost: 20,
  },
  blackMarket: {
    id: 'blackMarket',    
    name: 'Black Market',
    effect: 'Sell Soylent for 4 credits a piece',
    points: 6,
    cost: 30,
  },
  cloning: {
    id: 'cloning',    
    name: 'Cloning',
    effect: '+1 Colonist, Colonist Hack',
    points: 6,
    cost: 30,
  },
  engine: {
    id: 'engine',    
    name: 'Engine',
    effect: 'Trade Unobtanium for 3 Colonists each',
    points: 6,
    cost: 40,
  },
  culturalHeritage: {
    id: 'culturalHeritage',    
    name: 'Cultural Heritage',
    effect: 'Bonus points: +1 / monument',
    points: 8,
    cost: 50,
  },
  kingOfSpace: {
    id: 'kingOfSpace',    
    name: 'King of Space',
    effect: 'Bonus points: +1 / planet',
    points: 8,
    cost: 60,
  },
}
